name: Build PDF

on:
  push:
    paths:
      - '**.tex'

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install LaTeX
      run: sudo apt-get update && sudo apt-get install -y texlive-latex-base
    - name: Compile PDF
      run: pdflatex A6000_Server_Documentation.tex
    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: A6000_Server_Documentation_PDF
        path: A6000_Server_Documentation.pdf
